### ISSUE TITLE
Boot fail with USB Drive Connected to Onboard Port

### ISSUE THREAD

**Issue by madirishman** [KaOSx/apps#114]
#### Submission type

  - [X ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> Plasma Wayland 2017.04

#### Used repositories

> Default…

#### Expected behaviour

> Normal Boot

#### Actual behaviour

> exit_boot() failed! and efi_main() failed

#### Steps to reproduce the problem

> Reboot with USB Drive mounted. Happens only if direct ported, if connected through a hub it does not.

#### System info link created by Octopi > Tools > SysInfo

> Moved to a different System cannot provide.

**Comment by demmm** [comment]
Without system info nothing that can be done with this report.  Only option is to guess, your USB connector caused the UUID to be changed, thus fstab & EFI are looking for a non existing option.

But without further info there is no option but to close this report.  Especially since it is stated system is not on KaOS.
