### ISSUE TITLE
Make 'isowriter' app more cross-distro

### ISSUE THREAD

**Issue by notuxius** [KaOSx/apps#128]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

#### Package name & version you are having issues with or have a request for

> isowriter-1.1.8-1

#### Used repositories

> Manjaro is used

#### Expected behaviour

> Ability to launch 'isowriter' in Manjaro or Nurunner (and in other Arch derivatives)

#### Actual behaviour

> Initial " xdg-su: unexpected option '-c' " error on launch in Manjaro

#### System info link created by Octopi > Tools > SysInfo

> I'm not seeing 'Octopi > Tools > SysInfo' entry in Octopi 0.8.8.5 - link to screenshot with system info - https://www.dropbox.com/s/mnddx5uo0907jdp/isowriter.png?dl=0

**Comment by demmm** [comment]
KaOS is a complete independ distribution.  It is not based on Arch, application build here are not compatible with the way Arch lays out it's base system or toolchain used.
https://kaosx.us/about/based/

Isowriter is tested on others, in fact just last week it was added to Gentoo based.  So make sure you actually build from git sources for your distribution.
https://github.com/KaOSx/isowriter
See the README for build instructions.

If you have further requests for Isowriter, do so in the above link, this bug tracker is for KaOS repositories (as you noted, you can't even file a proper report since you do not have the needed SysInfo tool).
