### ISSUE TITLE
Kde panel reset [Bug]

### ISSUE THREAD

**Issue by Fabioah** [KaOSx/apps#156]
Hi, I have recently installed kaos and to customize the panel I removed some objects and moved others. After this I don't know what happened but every time I reboot my pc some objects (clock and system try) shift from right corner to left

Clock and try icons should be on the right corner.
https://ptpb.pw/pNwt
Everything is updated and I use just default repositories.

![screenshot_20180603_211824](https://user-images.githubusercontent.com/34600288/40890292-181c273e-6774-11e8-8051-7d0f4fea73bd.png)

**Comment by Fabioah** [comment]
Updated. I don't know which is the application I have to consider to write his version. I will try with a new user.

**Comment by demmm** [comment]
Again, no idea if this is a bug report for a KaOS install, what you have done with the system and so on.  That is why when you opened this "report" you were presented with a from to provide basic info.  Please provide it, otherwise nothing can be done with this report and needs to be closed.

**Comment by Fabioah** [comment]
I'm sorry I don't know how to make this infos useful

**Comment by demmm** [comment]
When you opened this, you got this form:
https://github.com/KaOSx/apps/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by demmm** [comment]
Also will be helpful for you to read:
https://kaosx.us/docs/

**Comment by Fabioah** [comment]
I have reported every information required by that form

**Comment by demmm** [comment]
Thanks, I presume you edited the first post and added the link?

Anyway, since you installed nvidia-bumblebee without nvidia-bumblebee-utils, there will be a lot more wrong with your graphics then just the panel.
Did you have this issue in live mode?  Did you have this issue when you first booted into the new install, before removing libgl and installing nvidia?  Are you sure this system can handle the latest nvidia?  Or does it need the older nvidia 390xx?
To test all of this, remove all nvidia packages and re-add libgl.  If you need help with this, see:
https://kaosx.us/docs/hybrid_gfx/
Reboot after removing all nvidia and see if using PRIME fixes your issue, or just using the intel card does the trick.

**Comment by Fabioah** [comment]
Yes I added the link after first answer but maybe github did not updated that. Anyway I have restored libgl to prevent other errors. I noticed that I removed task manager objects from the panel some day ago. I tried to add this now to separe clock and system try from icons but when I reboot it returns like the image on the first comment. Maybe the The panel reset itself whatever I do. I'm sorry but I can't remember if this issue appear before or after the installation of nvidia driver.

**Comment by demmm** [comment]
To see if it is a driver issue, or some settings you adjusted for your user, test first with a new clean user, if that fixes, you will need to get som new clean files in your ~/config.

**Comment by Fabioah** [comment]
Yes a clean user has not this issue. So this is not a bug but my mistake?

**Comment by demmm** [comment]
Yes, this a is some corruption in an rc file. most probably ~/.config/plasma-org.kde.plasma.desktop-appletsrc
Remove or rename that file, and let Plasma create a new clean one (do this when logged as that current user).

**Comment by Fabioah** [comment]
Ok, removing that file solved the issue. Thank you for your patience.
