### ISSUE TITLE
Krfb: missing library libidn.so.11

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#165]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> … krfb 18.08.1

#### Used repositories

> … core, main, apps 

#### Expected behaviour

> … launches

#### Actual behaviour

> … does not launch

#### Steps to reproduce the problem

> … hit krfb in the Konsole

#### System info link created by Octopi > Tools > SysInfo

> … https://ptpb.pw/f1W8

Reproduced on 2 devices

**Comment by demmm** [comment]
Confirmed.  Something was missed in the libidn rebuilds last May. It can't be krfb itself, since it has been rebuild numerous times since.
https://github.com/KaOSx/main/commit/8084d7f0af5eced00c208b75deb261f86d2fd0f8
https://github.com/KaOSx/main/commit/66bf8b2e053b7d40cb38a88a03015dd89b1d55f3
https://github.com/KaOSx/main/commit/680bb242dd75120f2d52d1152e853f991c8e1239
I'll check later if it is libvncserver.

**Comment by ShalokShalom** [comment]
So this means krfb is not working since May? Thanks for your quick investigation. 
Nice day

**Comment by ShalokShalom** [comment]
OK, fine. 

Thanks a lot ^-^
