### ISSUE TITLE
Can't pin Godot Engine to Task Manager

### ISSUE THREAD

**Issue by EQLucky** [KaOSx/apps#179]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> Godot Engine 3.1-1

#### Used repositories

> Apps

#### Expected behaviour

> Being able to ping the app to the Task Manager.

#### Actual behaviour

> "Pin" option is greyed out.

#### Steps to reproduce the problem

> Install Godot, launch it and trying to pint it.

#### System info link created by Octopi > Tools > SysInfo

> https://pastebin.com/qDSz4mqi

**Comment by demmm** [comment]
Checked upstream bug reports? Is this a KaOS packaging issue, Plasma issue or general upstream known bug?

**Comment by EQLucky** [comment]
Hey, Demm.

AFAIK this isn't a general upstream issue. Checked their github and I didn't find anything.
About Plasma, I don't remember when this issue started bothering me, since I launch it from time to time. I'll check the system in few hours and I'll report the results.

**Comment by demmm** [comment]
Never used godot before, but checked it now.  There is no issue pinning it from the startmenu, pinning is only greyed out when godot is started, then present in the panel.
Pinning from startmenu results in correct starting of the app too, so no idea how this can be a packaging issue.....

**Comment by demmm** [comment]
Found the issue, it is the new naming of the .desktop file, see commit for updating to 3.1:
https://github.com/KaOSx/apps/commit/3dfa7196d996d5d8178a126703a948dde08bae44#diff-6eb161b820f453e8e35eee2b55e1605dR30
When you copy the .desktop to old `godot.desktop`, pinning just works.  Seems Plasma can't handle the new (upstream) naming scheme.  For now, I can rebuild and rename the new upstream way, but it really should be brought to their attention, that pinning broke in plasma due to this.
