### ISSUE TITLE
Thunderbird v68.2.0 resets setings to default!

### ISSUE THREAD

**Issue by SzykCech4** [KaOSx/apps#189]
#### Submission type

  - [ ] Bug report

#### Package name & version you are having issues with or have a request for

> Thunderbird v68.2.0

#### Used repositories

> ?

#### Expected behaviour

> Upadate setings and run with them nicely.

#### Actual behaviour

> Thunderbird v68.2.0 resets setings to default after update from older version.

#### Steps to reproduce the problem

> Use some old instaler to instal KaOS - DO NOT USE UPDATE DURING INSTALATION.
> Configure your email acount and news groups.
> Update system to recent version.

#### Work around:
> Edit ~/.thunderbird/profiles.ini in text editor and correct it in sensible way. You can recognize what directories were created before currently used. You can also see that some of older directories remain in the config file - just copy them in to remain/rest places.

#### System info link created by Octopi > Tools > SysInfo

> [octopi-sysinfo-1928786029.log](https://github.com/KaOSx/apps/files/3768771/octopi-sysinfo-1928786029.log)

**Comment by demmm** [comment]
Thunderbird is pure what upstream ships for KaOS, it is not compiled, just packaged the provided the binary, so certainly not a KaOS/packaging issue.
Since Thunderbird changed so much for 68, see the forum to prepare your settings for new ways of Thunderbird.
https://forum.kaosx.us/d/2445-update-thunderbird/3
