### ISSUE TITLE
LibreCalc & LibreDraw fail to save.

### ISSUE THREAD

**Issue by NoSavvy** [KaOSx/apps#221]
#### Submission type

  - [x] Bug report
  

#### Package name & version you are having issues with or have a request for

> …Libreoffice-24.2.0.3-2 and Libreoffice-24.2.0.3-3 

#### Used repositories
KaOS main repos

> …KaOS main repos

#### Expected behaviour
Choose save, enter name and enter.
> …Choose save, enter name and enter.

#### Actual behaviour

> …Do the above and save box continues to loop, having to exit unsaved.

#### Steps to reproduce the problem

> …Attempt to save a file.

#### System info link created by Octopi > Tools > SysInfo

> …[octopi-sysinfo-1753098507.log](https://github.com/KaOSx/apps/files/14285673/octopi-sysinfo-1753098507.log)

**Comment by demmm** [comment]
Is this only an issue with native save file dialog?  Have you tried adjusting the Libreoffice settings and use Options > LibreOffice > General > enable Use LibreOffice dialogs?

**Comment by NoSavvy** [comment]
Yes using that method it appears to be working OK. I had tried almost every other option apart from that one.
So for me solved using that option.

**Comment by demmm** [comment]
Upstream bug reports are now up, looks to be a Plasma issue, since the one at libreoffice was closed:
https://bugs.kde.org/show_bug.cgi?id=481287
https://bugs.documentfoundation.org/show_bug.cgi?id=159701

As noted in the kde.org report, starting with `SAL_USE_VCLPLUGIN=qt6 libreoffice` is also a possible workaround.
