### ISSUE TITLE
plasmashell resources consuming

### ISSUE THREAD

**Issue by demianx681** [KaOSx/apps#77]
#### Submission type

  -  Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> plasma-workspace 5.7.3-5  plasma-framework 5.24.0-3
#### Used repositories

> core, main, apps 
#### Expected behaviour

> less need for hw resources 

#### Actual behaviour
> plasmashell processor use skyrockets to 25% and so does dedicated memory (2 Mb) , the whole GUI becomes unresponsive and constant flickering are experienced

#### Steps to reproduce the problem

> Still haven't found a pattern in all this. The only workaround is to reboot the system

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/9d8238d3368a24dc7cd54f09bd931787

**Comment by demmm** [comment]
Most of the time theses issues are due to incompatible themes/plasmoids.
Have you tried with a new user?
In this case, your journal is full of wifi warnings.  Any option to turn of wifi and use a wired internet connection?

A full log will be needed if the above 2 don't fix.  Once the resource use goes up, run:
```
sudo journalctl -r
```
hit "enter" until you have enough output to show the last 20-30 minutes and paste it here.

**Comment by demmm** [comment]
No further response from submitter, closing.
