### ISSUE TITLE
Okular: 'change light & dark colors' broken

### ISSUE THREAD

**Issue by GitRASQ** [KaOSx/apps#82]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> okular kf 5.25

#### Used repositories

> default

#### Expected behaviour

> In settings > configure okular > accessibility, there is an option to change light & dark colors. I set the light (background) color to black and the dark (text) color to light gray. 

#### Actual behaviour

> The background is dark gray, and the text is light gray around the edges and black in the middle. After turning off text anti-aliasing, the text is black.
http://i.imgur.com/F13sAf4.png
http://i.imgur.com/1lNbGvG.png

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/2120ce016cfc9864a87725f7a300f6e1

Edit: installed yesterday from .iso found here: https://forum.kaosx.us/d/1599-test-cycle-2016-09-iso

**Comment by demmm** [comment]
As you read in that forum post, test ISOs use the build repo.  You can not use this ISO without enabling [build], many you install will be broken due to API changes in updates in build, so this bug report cannot be used as is.
Okular is not fully ported yet, thus the unstable frameworks build for KaOS, but you can check upstream reports to see if this is already mentioned.
