### ISSUE TITLE
Show file type folder in Dolphins sidebar

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/apps#92]
#### Submission type

  - [x] Feature Request

#### Package name & version you are having issues with or have a request for

> … Dolphin 16.12

#### Proposed behaviour

![screenshot_20170108_113143](https://cloud.githubusercontent.com/assets/6344099/21749065/0c52d874-d596-11e6-96ad-019540536bf3.png)

**Comment by demmm** [comment]
Closing this feature request here since ti will not be adjusted in packaging.
A dolphinrc file has been added to the ISO creation:
https://github.com/KaOSx/live-uefi/blob/master/configs/shared/overlay/home/live/.config/dolphinrc

If this works well in Live mode, then it will be added to installs too.

Please open a new issue in live-uefi if you want different adjustments for dolpinrc.
https://github.com/KaOSx/live-uefi
